import {
    ChevronLeft,
    Command,
    X,
    Home,
    MailCheck,
    AlertCircle,
    Check,
    EyeOff,
    Loader2,
    type LucideIcon,
    Eye,
    Search,
    Bell,
    Moon,
    HelpCircleIcon,
    Grip,
    ChevronDown,
    Pencil,
    Upload,
    MoveRight,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
    upload: Upload,
    pencil: Pencil,
    chevron_down: ChevronDown,
    grip: Grip,
    logo: Command,
    chevron_left: ChevronLeft,
    close: X,
    home: Home,
    mail_check: MailCheck,
    alert_circle: AlertCircle,
    check: Check,
    eye: Eye,
    eye_off: EyeOff,
    loader: Loader2,
    search: Search,
    noti: Bell,
    moon: Moon,
    circle_help: HelpCircleIcon,
    move_right: MoveRight,
};
